export type LangType = {
    [key: string]: string | LangType;
}

const lang: LangType = {
    'en': {
        calc_header: 'Cryptocurrency calculator and converter',
        calc_placeholder: 'Enter amount to convert',
        calc_popular_exchanges: 'Popular options for converting cryptocurrencies',
        chart_line_chart: 'Line Chart',
        chart_candle_chart: 'Candlestick Chart',
        chart_price: 'Price',
        coin_list_name: 'Name',
        coin_list_price: 'Price',
        coin_list_marketCup: 'Market Cup',
        coin_list_marketPercent: 'Value (24h %)',
        coin_list_totalVolume: 'Total Volume',
        coin_list_circulatingSupply: 'Circulating Supply',
        placeholder_searchInput: 'Enter currency name...',
        marketCup_rank: 'Rank:',
        tab_mainPage: 'Main Page',
        tab_calcPage: 'Calculator',
        tab_newsPage: 'News Page',
        tab_chartPage: 'Chart Page',
        tab_watchPage: 'Watchlist',
        tab_portfolioPage: 'Portfolio',
        auth_signin: 'Sign In',
        auth_signup: 'Sign Un',
        auth_savebutton: 'Save',
        auth_username: 'Name',
        auth_email: 'Email',
        auth_password: 'Password',
        auth_password_placeholder: 'password must be more than 6 characters',
        auth_your_email: 'Your email',
        auth_your_password: 'Your password',
        port_add: 'add',
        port_buy: 'buy',
        port_sell: 'sell',
        port_delete: 'delete',


    },
    'ru': {
        calc_header: 'Калькулятор и конвертер криптовалют',
        calc_placeholder: 'Введите сумму для конвертации',
        calc_popular_exchanges: 'Популярные варианты конвертации криптовалют',
        chart_line_chart: 'Линейный график',
        chart_candle_chart: 'Свечной график',
        chart_price: 'Цена:',
        coin_list_name: 'Наименование',
        coin_list_price: 'Текущая цена',
        coin_list_marketCup: 'Рыночная капитализация',
        coin_list_marketPercent: 'Объём (24ч %)',
        coin_list_totalVolume: 'Объём сделок',
        coin_list_circulatingSupply: 'Циркулирующее предложение',
        placeholder_searchInput: 'Введите название валюты...',
        marketCup_rank: 'Ранг:',
        tab_mainPage: 'Главная',
        tab_calcPage: 'Калькулятор валют',
        tab_newsPage: 'Новости',
        tab_chartPage: 'График',
        tab_watchPage: 'Избранное',
        tab_portfolioPage: 'Портфолио',
        auth_signin: 'Регистрация',
        auth_signup: 'Войти',
        auth_savebutton: 'Сохранить',
        auth_username: 'Имя',
        auth_email: 'Емэйл',
        auth_password: 'Пароль',
        auth_password_placeholder: 'Пароль должен быть более 6 символов',
        auth_your_email: 'Ваш емэйл',
        auth_your_password: 'Ваш пароль',
        port_add: 'Добавить',
        port_buy: 'Купить',
        port_sell: 'Продать',
        port_delete: 'Удалить',




    },
    'by': {
        calc_header: 'Калькулятар і канвэртар крыптавалют',
        calc_placeholder: 'Увядзіце суму для канвертавання',
        calc_popular_exchanges: 'Папулярныя варыянты канвертавання крыптавалют',
        chart_line_chart: 'Лінейны графік',
        chart_candle_chart: 'Свячны графік',
        chart_price: 'Кошт',
        coin_list_name: 'Назва',
        coin_list_price: 'Бягучы кошт',
        coin_list_marketCup: 'Рынкавая капіталізацыя',
        coin_list_marketPercent: 'Аб`ём (24г %)',
        coin_list_totalVolume: 'Агульны аб`ём',
        coin_list_circulatingSupply: 'Абаротнае забеспячэнне',
        placeholder_searchInput: 'Увядзіце назву валюты...',
        marketCup_rank: 'Ранг:',
        tab_mainPage: 'Галоўная',
        tab_calcPage: 'Калькулятар',
        tab_newsPage: 'Навіны',
        tab_watchPage: 'Абранае',
        tab_portfolioPage: 'Партфоліо',
        auth_signin: 'Зарэгістравацца',
        auth_signup: 'Уваход',
        auth_savebutton: 'Захаваць',
        auth_username: 'Імя',
        auth_email: 'Емэйл',
        auth_password: 'Пароль',
        auth_password_placeholder: 'Пароль павінен быць больш за 6 сімвалаў',
        auth_your_email: 'Ваш емэйл',
        auth_your_password: 'Ваш пароль',
        port_add: 'Дадаць',
        port_buy: 'Купіць',
        port_sell: 'Прадаць',
        port_delete: 'Выдаліць',


    }
};

export default lang;